### ISSUE TITLE
Example.py connection error

### ISSUE THREAD

**Issue by Mathijs-me** [EnergieID/KNMI-py#10]
from:

from knmi import knmi, metadata

# print(metadata.stations)# provides a list of all available stations
# print(metadata.variables)# provides a list of all variables and explanations

station_de_bilt=260
station_eelde=280
print("Ophalen dagdata")
df = knmi.get_day_data_dataframe(stations=[station_de_bilt,station_eelde],start="20200501",end="20200601" )
print(df)
print("Ophalen uurdata")
df = knmi.get_hour_data_dataframe(stations=[station_de_bilt,station_eelde],start="2020080101",end="2020080105" )
print(df)
print("Ophalen uurdata alleen temp en zon")
df = knmi.get_hour_data_dataframe(stations=[station_de_bilt,station_eelde],start="2020080101",end="2020080124" ,variables=['TEMP','SUNR'])
print(df)

ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'De externe host heeft een verbinding verbroken', None, 10054, None))

**Comment by cfernhout** [comment]
This is because the http://projects.knmi.nl is down. This is not an issue from this package.

**Comment by teije01** [comment]
Closing because problem no longer persists
