### ISSUE TITLE
StopIteration - stations_raw = [line.strip("# ") for line in stations_raw]  # strip away the prefix '# '

### ISSUE THREAD

**Issue by olivierbrouw** [EnergieID/KNMI-py#11]
Hello, 

First of all, great and useful package!

I experienced an error when using the function 'get_hour_data_dataframe'. Below the code I runned with the error message. Don't know if the issue is known and already worked on, otherwise I will try fixing it myself.

Best regards,

Olivier

df = knmi.get_hour_data_dataframe(stations=[260,280],start="2020080101",end="2020080105" )

/local_disk0/pythonVirtualEnvDirs/virtualEnv-810100ee-3db0-4457-9149-f4b75ed9df4f/lib/python3.7/site-packages/knmi/parsers.py in parse_day_data(raw)
     28 
     29     # parse the station list
---> 30     stations_raw = next(chunks)
     31     stations_raw = [line.strip("# ") for line in stations_raw]  # strip away the prefix '# '
     32     stations = {}

StopIteration:

**Comment by jeroendevriesbakker** [comment]
Hi Olivier,

I get the same error. I have experienced this error since a few weeks now. Did you fixed this? 

Best regards,

Jeroen

**Comment by olivierbrouw** [comment]
Hi Jeroen, 

I reproduced the request and checked the KNMI site. Seems that the API of the KNMI site is not working and they are busy to resolve the issue. See the message on their site:
* https://www.knmi.nl/kennis-en-datacentrum/achtergrond/data-ophalen-vanuit-een-script

Hopefully they fix the issue soon. If you have an alternative please let me know. 

Best regards,

Olivier

**Comment by jeroendevriesbakker** [comment]
Hi Olivier,

The only alternative they give is downloading a file with "wget". That's no proper alternative for my solution. Hopefully they will fix this soon!

**Comment by spiegelffv** [comment]
Hi all,

i noticed this API-issue on 13-2-2021.  They say that it will be fixed by "friday"....
I was not able to contact them; "contact-form" not working.

**Comment by randyrosink** [comment]
Hi,
Still not working on my side, any news on this topic?

**Comment by spiegelffv** [comment]
No news from KNMI - they changed the comment : "we are working hard to find an alternative ...."

**Comment by jeroendevriesbakker** [comment]
I think the KNMI don't have an solution. I will gonna try to receive the same weather information with an anonymous API key.

**Comment by jeroendevriesbakker** [comment]
Still not working, i have an work arround using "wget" downloading the file to my client.

**Comment by ncsmits** [comment]
> Still not working, i have an work arround using "wget" downloading the file to my client.

Would you mind sharing a brief example? Would help me a lot!

**Comment by spiegelffv** [comment]
I changed to openweathermap.org:
must create an account for the api-key.

python:
import requests as req
r = req.get('http://api.openweathermap.org/data/2.5/weather?q=Meppel,nl&appid=993915c716cdd661e458e7321c6801bd&units=metric')
x = r.json()
temp_min = x['main']['temp_min']
temp_max = x['main']['temp_max']
luchtdruk = x['main']['pressure']   #hp
vochtigheidsgraad = x['main']['humidity']   #%
windrichting = x['wind']['deg']     #graden
windkracht = x['wind']['speed']     #m/sec

etc..

**Comment by jeroendevriesbakker** [comment]
I still use KNMI data:

import os
if os.path.exists("etmgeg_269.zip"):
  os.remove("etmgeg_269.zip")
else:
  print("The file does not exist")

import wget 
url = 'https://cdn.knmi.nl/knmi/map/page/klimatologie/gegevens/daggegevens/etmgeg_269.zipstns=269&vars=FG:TG:RH&start=2019010101'

filename = wget.download(url)
filename

df= pd.read_csv('etmgeg_269.zip', skiprows=47)

**Comment by hetspookjee** [comment]
The issue seems to be that the KNMI has changed both the API return format, and the way the response needs to be structured.

Currently the parameters are passed as a dictionary through the [data header](https://github.com/EnergieID/KNMI-py/blob/master/knmi/knmi.py#L59).

However, the [new API documentation](https://www.knmi.nl/kennis-en-datacentrum/achtergrond/data-ophalen-vanuit-een-script) expects it to be done instead with a formatted string.

I got it to work by calling the below. Do note that the URL has also changed!

```python
url = "https://www.daggegevens.knmi.nl/klimatologie/daggegevens"
enc_params=urllib.parse.urlencode(params, safe=':')
r = requests.post(url=url, data=enc_params)
```

Below is a complete working example through Python. The parser was to big of a chunk to chew and update it entirely. I am afraid a big rewrite is needed due to the change in return format and the way the parser is setup. You have to include the legend mapping yourself, though it is still available in 

```python
import knmi
print(knmi.variables)
```

Below a working example:

```python
import requests
import urllib
import pandas as pd
from io import StringIO
from datetime import datetime, timedelta

end = datetime.now()
start = end - timedelta(days=365 * 30)
inseason = False
# variables=['TG:TN:EV24']
variables = ["SQ"]
stations = ["260"]


url = "https://www.daggegevens.knmi.nl/klimatologie/daggegevens"
params = {
    "stns": ":".join(str(station) for station in stations),
}

params.update({"vars": ":".join(variables)})
enc_params = urllib.parse.urlencode(params, safe=":")
r = requests.post(url=url, data=enc_params)
r.raise_for_status()
raw = r.text
chunk = raw.split("# ")[-1]
df = pd.read_csv(StringIO(chunk), sep=",")
df
```

**Comment by teije01** [comment]
@olivierbrouw I have recently worked on a fix for this problem. Version `0.1.9` was released to [pypi](https://pypi.org/project/knmi-py/#history) this monday. Please have a look if this fixes your problem.

**Comment by teije01** [comment]
Closing because this should be fixed by now.
