### ISSUE TITLE
not all stations are active

### ISSUE THREAD

**Issue by FrankBoermanTenneT** [EnergieID/KNMI-py#15]
a lot of stations listed in the station list of this package are not listed on the page here: https://www.daggegevens.knmi.nl/klimatologie/uurgegevens and return http 500 when trying to query them. Perhaps better to remove them from the package? Or where do those come from?

**Comment by JrtPec** [comment]
Hi Frank! As you can see, this package has not seen too many developments over the last few years. Probably KNMI has updated many things in the meantime, so I'm sure there are a lot of changes that can be made here as well! Go ahead!
