### ISSUE TITLE
df.disclaimer doesn't work, 

### ISSUE THREAD

**Issue by MaykThewessen** [EnergieID/KNMI-py#17]
print(df.disclaimer)
print(df.stations)
print(df.legend)

df = df.rename(columns=df.legend)

`knmi.disclaimer
Traceback (most recent call last):

  Cell In[31], line 1
    knmi.disclaimer

AttributeError: module 'knmi' has no attribute 'disclaimer'`

**Comment by teije01** [comment]
This has indeed changed back in 2018-11-26 in revision 00d28a979357ac5a60916c7e416dcb5e113f35f4

> removes disclaimer, stations and legend from the dataframe (because it produces pandas warnings). If you want this data, you have to use `get_day_data_raw` instead.

The documentation should probably reflect this too.
