### ISSUE TITLE
"variables" argument in `get_day_data_dataframe` returns all variables

### ISSUE THREAD

**Issue by SytzeSimonse** [EnergieID/KNMI-py#7]
When I call the function `get_day_data_dataframe` for a specified variable (e.g. `TEMP`), the returned DataFrame instead contains all variables.

For example:
`knmi.get_day_data_dataframe([260], dt.datetime(2020, 2, 2), dt.datetime(2020, 5, 2), ['TEMP'])`
 returns a DataFrame with 40 columns.

**Comment by RoelantDL** [comment]
The third parameter is "inseason" not "variables". Either specify the third parameter or add the "variables" param.
`knmi.get_day_data_dataframe([260], dt.datetime(2020, 2, 2), dt.datetime(2020, 5, 2), variables=['TEMP'])
`
It should return a dataframe with only the TEMP variables.
